base: !include base.yaml
run_name: 'UNetShapeNetCar'
project_name: "ShapeNetCar"

# train setting
num_epochs: 100
batch_size: 1
eval_batch_size: 1
lr: 0.001
device: "gpu:2"
save_interval: 50

# model setting
mode: "train"
model: "Transolver"
model_name: "efficientnet-b0"
in_channels: 1
out_channels: 1 # pressure
num_levels: 4
hidden_channels: 64
use_position_input: False
use_attn: false

# dataset setting
data_module: "CFDSDFDataModule"
data_dir: "./Training/Dataset_1/Feature_File"
test_data_dir: "./Test/Dataset_1/Feature_File"
n_train: 100
n_test: 50
sdf_spatial_resolution: [64, 64, 64]
point_data_pos: "press on mesh points" 

# eval setting
write_to_vtk: True
out_keys: ["pressure"]
track : "Dataset_1_pressure"

