base: !include base.yaml
run_name: 'UNetShapeNetCar'
project_name: "ShapeNetCar"

# train setting
num_epochs: 50
batch_size: 1
eval_batch_size: 1
lr: 0.0005
device: "gpu:0"
save_interval: 50

# model setting
mode: "train"
model: "Transolver"
model_name: "efficientnet-b0"
in_channels: 1
out_channels: 3 # velociy x, velociy y, velociy z
num_levels: 4
hidden_channels: 64
use_position_input: False
use_attn: false

# dataset setting
data_module: "VelocityDataModule"
train_data_dir: "./Training/Dataset_2/Feature_File/"
test_data_dir: "./Test/Dataset_2/Feature_File/"
sdf_spatial_resolution: [64, 64, 64]
point_data_pos: "press on mesh points" 

# eval setting
write_to_vtk: false
out_keys: ["velocity"]
track : "Dataset_1_velocity"
